---

- name: "MEDIUM | UBTU-18-010002 | PATCH | The Ubuntu operating system must initiate session audits at system startup."
  block:
      - name: "MEDIUM | UBTU-18-010002 | AUDIT | The Ubuntu operating system must initiate session audits at system startup. | Get GRUB_CMDLINE_LINUX"
        shell: grep "GRUB_CMDLINE_LINUX=" /etc/default/grub | cut -f2 -d'"'
        changed_when: false
        failed_when: false
        register: ubtu_18_010002_cmdline_settings

      - name: "MEDIUM | UBTU-18-010002 | PATCH | The Ubuntu operating system must initiate session audits at system startup. | Add setting if audit doesn't exist"
        lineinfile:
            path: /etc/default/grub
            regexp: '^GRUB_CMDLINE_LINUX='
            line: 'GRUB_CMDLINE_LINUX="{{ ubtu_18_010002_cmdline_settings.stdout }} audit=1"'
        notify: update grub
        when: "'audit=' not in ubtu_18_010002_cmdline_settings.stdout"

      - name: "MEDIUM | UBTU-18-010002 | PATCH | The Ubuntu operating system must initiate session audits at system startup. | Add setting if audit exists"
        replace:
            path: /etc/default/grub
            regexp: 'audit=([0-9]+)'
            replace: 'audit=1'
        notify: update grub
        when: "'audit=' in ubtu_18_010002_cmdline_settings.stdout"
  when:
      - ubtu_18_010002
  tags:
      - UBTU-18-010002
      - CAT2
      - CCI-001464
      - SRG-OS-000254-GPOS-00095
      - SV-219149r610963_rule
      - V-219149
      - grub

- name: "MEDIUM | UBTU-18-010003 | AUDIT | Ubuntu operating systems handling data requiring data at rest protections must employ cryptographic mechanisms to prevent unauthorized disclosure and modification of the information at rest."
  block:
      - name: "MEDIUM | UBTU-18-010003 | AUDIT | Ubuntu operating systems handling data requiring data at rest protections must employ cryptographic mechanisms to prevent unauthorized disclosure and modification of the information at rest. | Get encrypted partitions"
        shell: more /etc/crypttab | sed 1d
        changed_when: false
        failed_when: false
        register: ubtu_18_010003_crypttab_status

      - name: "MEDIUM | UBTU-18-010003 | AUDIT | Ubuntu operating systems handling data requiring data at rest protections must employ cryptographic mechanisms to prevent unauthorized disclosure and modification of the information at rest. | Alert no partitions are encrypted"
        debug:
            msg:
                - "Warning!! There no encrypted partitions. Please make sure all permenant partitions are encrypted"
        when: ubtu_18_010003_crypttab_status.stdout | length == 0

      - name: "MEDIUM | UBTU-18-010003 | AUDIT | Ubuntu operating systems handling data requiring data at rest protections must employ cryptographic mechanisms to prevent unauthorized disclosure and modification of the information at rest. | Alert no partitions are encrypted"
        debug:
            msg:
                - "Warning!! Please review that no permenant partitions are missing. All permenant partitions need to be encrypted"
                - "{{ ubtu_18_010003_crypttab_status.stdout_lines }}"
        when: ubtu_18_010003_crypttab_status.stdout | length > 0
  when:
      - ubtu_18_010003
  tags:
      - UBTU-18-010003
      - CAT2
      - CCI-001199
      - CCI-002475
      - CCI-002476
      - SRG-OS-000185-GPOS-00079
      - SV-219150r610963_rule
      - V-219150
      - encryption
      - mounts

- name: "MEDIUM | UBTU-18-010016 | PATCH | Advance package Tool (APT) must be configured to prevent the installation of patches, service packs, device drivers, or Ubuntu operating system components without verification they have been digitally signed using a certificate that is recognized and approved by the organization."
  block:
      - name: "MEDIUM | UBTU-18-010016 | AUDIT | Advance package Tool (APT) must be configured to prevent the installation of patches, service packs, device drivers, or Ubuntu operating system components without verification they have been digitally signed using a certificate that is recognized and approved by the organization. | Find AllowUnauthenticated true"
        shell: "grep 'AllowUnauthenticated \"true\"' /etc/apt/apt.conf.d/* | cut -d: -f1"
        changed_when: false
        failed_when: false
        register: ubtu_18_010016_apt_allowunauthenticated_status

      - name: "MEDIUM | UBTU-18-010016 | PATCH | Advance package Tool (APT) must be configured to prevent the installation of patches, service packs, device drivers, or Ubuntu operating system components without verification they have been digitally signed using a certificate that is recognized and approved by the organization. | Fix AllowUnauthenticated to false"
        replace:
            path: "{{ item }}"
            regexp: 'AllowUnauthenticated "true"'
            replace: 'AllowUnauthenticated "false"'
        with_items:
            - "{{ ubtu_18_010016_apt_allowunauthenticated_status.stdout_lines }}"
        when: ubtu_18_010016_apt_allowunauthenticated_status.stdout | length > 0
  when:
      - ubtu_18_010016
  tags:
      - UBTU-18-010016
      - CAT2
      - CCI-001749
      - SRG-OS-000366-GPOS-00153
      - SV-219155r610963_rule
      - V-219155
      - apt

- name: "MEDIUM | UBTU-18-010017 | PATCH | The Ubuntu operating system must be configured so that Advance package Tool (APT) removes all software components after updated versions have been installed."
  block:
      - name: "MEDIUM | UBTU-18-010017 | AUDIT | The Ubuntu operating system must be configured so that Advance package Tool (APT) removes all software components after updated versions have been installed. | Find Remove-Unused-Kernel-Packages"
        shell: "grep -i 'remove-unused-kernel-packages \"false\"' /etc/apt/apt.conf.d/* | cut -d: -f1"
        changed_when: false
        failed_when: false
        register: ubtu_18_010017_remove_unused_kernel_packages_status

      - name: "MEDIUM | UBTU-18-010017 | AUDIT | The Ubuntu operating system must be configured so that Advance package Tool (APT) removes all software components after updated versions have been installed. | Find Remove-Unused-Dependencies"
        shell: "grep -i 'remove-unused-dependencies \"false\"' /etc/apt/apt.conf.d/* | cut -d: -f1"
        changed_when: false
        failed_when: false
        register: ubtu_18_010017_remove_unused_dependencies_status

      - name: "MEDIUM | UBTU-18-010017 | PATCH | The Ubuntu operating system must be configured so that Advance package Tool (APT) removes all software components after updated versions have been installed. | Set Remove-Unused-Kernel-Packages"
        lineinfile:
            path: "{{ item.path }}"
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
            create: true
            mode: 644
            owner: root
            group: root
        with_items:
            - { path: "{{ (ubtu_18_010017_remove_unused_kernel_packages_status.stdout | length == 0 ) | ternary('/etc/apt/apt.conf.d/50unattended-upgrades',ubtu_18_010017_remove_unused_kernel_packages_status.stdout) }}", regexp: 'Unattended-Upgrade::Remove-Unused-Kernel-Packages', line: 'Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";' }
            - { path: "{{ (ubtu_18_010017_remove_unused_dependencies_status.stdout | length == 0 ) | ternary('/etc/apt/apt.conf.d/50unattended-upgrades',ubtu_18_010017_remove_unused_dependencies_status.stdout) }}", regexp: 'Unattended-Upgrade::Remove-Unused-Dependencies', line: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";' }
        loop_control:
            label: "{{ item.line }}"
  when:
      - ubtu_18_010017
  tags:
      - UBTU-18-010017
      - CAT2
      - CCI-002617
      - SRG-OS-000437-GPOS-00194
      - SV-219156r610963_rule
      - V-219156
      - apt

# There is no mfetp package available. The McAfee instructions have you download the installer from their portal. This package may no longer be available
# - name: "MEDIUM | UBTU-18-010021 | PATCH | The Ubuntu operating system must deploy Endpoint Security for Linux Threat Prevention (ENSLTP)."
#   package:
#       name: mfetp
#       state: present
#   when:
#       - ubtu_18_010021
#       - '"mfetp" not in ansible_facts.packages'
#   tags:
#       - UBTU-18-010021
#       - CAT2
#       - CCI-001233
#       - SRG-OS-000191-GPOS-00080
#       - SV-219159r610963_rule
#       - V-219159
#       - ensltp

- name: "MEDIUM | UBTU-18-010022 | PATCH | The Ubuntu operating system must be configured to preserve log records from failure events."
  service:
      name: rsyslog
      state: started
      enabled: true
  when:
      - ubtu_18_010022
  tags:
      - UBTU-18-010022
      - CAT2
      - CCI-001665
      - SRG-OS-000269-GPOS-00103
      - SV-219160r610963_rule
      - V-219160
      - rsyslog

- name: "MEDIUM | UBTU-18-010023 | PATCH | The Ubuntu operating system must have an application firewall installed in order to control remote access methods."
  package:
      name: ufw
      state: present
  when:
      - ubtu_18_010023
  tags:
      - UBTU-18-010023
      - CAT2
      - CCI-002314
      - SRG-OS-000297-GPOS-00115
      - SV-219161r610963_rule
      - V-219161
      - ufw
      - firewall

- name: "MEDIUM | UBTU-18-010033 | PATCH | The Ubuntu operating system must be configured so that three consecutive invalid logon attempts by a user automatically locks the account until released by an administrator."
  block:
      - name: "MEDIUM | UBTU-18-010033 | AUDIT | The Ubuntu operating system must be configured so that three consecutive invalid logon attempts by a user automatically locks the account until released by an administrator. | Find pam_faillock.so authfail"
        shell: 'grep "auth.*\[default=die\].*pam_faillock.so" /etc/pam.d/common-auth'
        changed_when: false
        failed_when: false
        register: ubtu_18_010033_authfail_status

      - name: "MEDIUM | UBTU-18-010033 | AUDIT | The Ubuntu operating system must be configured so that three consecutive invalid logon attempts by a user automatically locks the account until released by an administrator. | Find pam_faillock.so authsucc"
        shell: grep "auth.*sufficient.*pam_faillock.so" /etc/pam.d/common-auth
        changed_when: false
        failed_when: false
        register: ubtu_18_010033_authsucc_status

      - name: "MEDIUM | UBTU-18-010033 | PATCH | The Ubuntu operating system must be configured so that three consecutive invalid logon attempts by a user automatically locks the account until released by an administrator. | Set if authsucc doesn't exist"
        pamd:
            name: common-auth
            type: "{{ ubtu18stig_pamd_faillock.type }}"
            control: "{{ ubtu18stig_pamd_faillock.control }}"
            module_path: "{{ ubtu18stig_pamd_faillock.module_path }}"
            new_type: auth
            new_control: sufficient
            new_module_path: pam_faillock.so
            module_arguments: authsucc
            state: "{{ ubtu18stig_pamd_faillock.state }}"
        when: ubtu_18_010033_authsucc_status.stdout | length == 0

      - name: "MEDIUM | UBTU-18-010033 | PATCH | The Ubuntu operating system must be configured so that three consecutive invalid logon attempts by a user automatically locks the account until released by an administrator. | Set if authfail doesn't exist"
        pamd:
            name: common-auth
            type: "{{ ubtu18stig_pamd_faillock.type }}"
            control: "{{ ubtu18stig_pamd_faillock.control }}"
            module_path: "{{ ubtu18stig_pamd_faillock.module_path }}"
            new_type: auth
            new_control: "[default=die]"
            new_module_path: pam_faillock.so
            module_arguments: authfail
            state: "{{ ubtu18stig_pamd_faillock.state }}"
        when: ubtu_18_010033_authfail_status.stdout | length == 0

      - name: "MEDIUM | UBTU-18-010033 | PATCH | The Ubuntu operating system must be configured so that three consecutive invalid logon attempts by a user automatically locks the account until released by an administrator. | Set authsucc does exist"
        pamd:
            name: common-auth
            type: auth
            control: sufficient
            module_path: pam_faillock.so
            module_arguments: authsucc
            state: args_present
        when: ubtu_18_010033_authsucc_status.stdout | length > 0

      - name: "MEDIUM | UBTU-18-010033 | PATCH | The Ubuntu operating system must be configured so that three consecutive invalid logon attempts by a user automatically locks the account until released by an administrator. | Set if authfail does exist"
        pamd:
            name: common-auth
            type: auth
            control: "[default=die]"
            module_path: pam_faillock.so
            module_arguments: authfail
            state: args_present
        when: ubtu_18_010033_authfail_status.stdout | length > 0

      - name: "MEDIUM | UBTU-18-010033 | PATCH | The Ubuntu operating system must be configured so that three consecutive invalid logon attempts by a user automatically locks the account until released by an administrator. | Update faillock.conf"
        lineinfile:
            path: /etc/security/faillock.conf
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
        with_items:
            - { regexp: '^#.*audit', line: audit }
            - { regexp: '^#.*silent', line: silent }
            - { regexp: '^deny.*=|^#.*deny.*=', line: "deny = {{ ubtu18stig_pamd_faillock.deny }}" }
            - { regexp: '^fail_interval.*=|^#.*fail_interval.*=', line: "fail_interval = {{ ubtu18stig_pamd_faillock.fail_interval }}" }
            - { regexp: '^unlock_time.*=|^#.*unlock_time.*=', line: "unlock_time = 0" }
  when:
      - ubtu_18_010033
  tags:
      - UBTU-18-010033
      - CAT2
      - CCI-000044
      - CCI-002238
      - SRG-OS-000021-GPOS-00005
      - SV-219166r802355_rule
      - V-219166
      - pamd

- name: "MEDIUM | UBTU-18-010035 | PATCH | The Ubuntu operating system must display the Standard Mandatory DoD Notice and Consent Banner before granting local access to the system via a graphical user logon. | Set banner settings"
  lineinfile:
      path: /etc/gdm3/greeter.dconf-defaults
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      insertafter: "{{ item.insertafter }}"
      create: true
      owner: root
      group: root
      mode: 0644
  notify:
      - reload gdm
      - dconf update
  with_items:
      - { regexp: '\[org\/gnome\/login-screen\]', line: '[org/gnome/login-screen]', insertafter: EOF }
      - { regexp: 'banner-message-enable', line: 'banner-message-enable=true', insertafter: '\[org\/gnome\/login-screen\]'}
      - { regexp: 'banner-message-text', line: 'banner-message-text={{ ubtu18cis_warning_banner }}', insertafter: 'banner-message-enable' }
  when:
      - ubtu_18_010035
      - ubtu18cis_desktop_required
  tags:
      - UBTU-18-010035
      - CAT2
      - CCI-000050
      - SRG-OS-000024-GPOS-00007
      - SV-219167r610963_rule
      - V-219167
      - banner

- name: "MEDIUM | UBTU-18-010036 | PATCH | The Ubuntu operating system must prevent direct login into the root account."

  when:
      - ubtu_18_010036
  tags:
      - UBTU-18-010036
      - CAT2
      - CCI-000770
      - SRG-OS-000109-GPOS-00056
      - SV-219168r610963_rule
      - V-219168
      - accounts

