---

- name: "MEDIUM | UBTU-18-010002 | PATCH | The Ubuntu operating system must initiate session audits at system startup."
  block:
      - name: "MEDIUM | UBTU-18-010002 | AUDIT | The Ubuntu operating system must initiate session audits at system startup. | Get GRUB_CMDLINE_LINUX"
        shell: grep "GRUB_CMDLINE_LINUX=" /etc/default/grub | cut -f2 -d'"'
        changed_when: false
        failed_when: false
        register: ubtu_18_010002_cmdline_settings

      - name: "MEDIUM | UBTU-18-010002 | PATCH | The Ubuntu operating system must initiate session audits at system startup. | Add setting if audit doesn't exist"
        lineinfile:
            path: /etc/default/grub
            regexp: '^GRUB_CMDLINE_LINUX='
            line: 'GRUB_CMDLINE_LINUX="{{ ubtu_18_010002_cmdline_settings.stdout }} audit=1"'
        notify: update grub
        when: "'audit=' not in ubtu_18_010002_cmdline_settings.stdout"

      - name: "MEDIUM | UBTU-18-010002 | PATCH | The Ubuntu operating system must initiate session audits at system startup. | Add setting if audit exists"
        replace:
            path: /etc/default/grub
            regexp: 'audit=([0-9]+)'
            replace: 'audit=1'
        notify: update grub
        when: "'audit=' in ubtu_18_010002_cmdline_settings.stdout"
  when:
      - ubtu_18_010002
  tags:
      - UBTU-18-010002
      - CAT2
      - CCI-001464
      - SRG-OS-000254-GPOS-00095
      - SV-219149r610963_rule
      - V-219149
      - grub

- name: "MEDIUM | UBTU-18-010003 | AUDIT | Ubuntu operating systems handling data requiring data at rest protections must employ cryptographic mechanisms to prevent unauthorized disclosure and modification of the information at rest."
  block:
      - name: "MEDIUM | UBTU-18-010003 | AUDIT | Ubuntu operating systems handling data requiring data at rest protections must employ cryptographic mechanisms to prevent unauthorized disclosure and modification of the information at rest. | Get encrypted partitions"
        shell: more /etc/crypttab | sed 1d
        changed_when: false
        failed_when: false
        register: ubtu_18_010003_crypttab_status

      - name: "MEDIUM | UBTU-18-010003 | AUDIT | Ubuntu operating systems handling data requiring data at rest protections must employ cryptographic mechanisms to prevent unauthorized disclosure and modification of the information at rest. | Alert no partitions are encrypted"
        debug:
            msg:
                - "Warning!! There no encrypted partitions. Please make sure all permenant partitions are encrypted"
        when: ubtu_18_010003_crypttab_status.stdout | length == 0

      - name: "MEDIUM | UBTU-18-010003 | AUDIT | Ubuntu operating systems handling data requiring data at rest protections must employ cryptographic mechanisms to prevent unauthorized disclosure and modification of the information at rest. | Alert no partitions are encrypted"
        debug:
            msg:
                - "Warning!! Please review that no permenant partitions are missing. All permenant partitions need to be encrypted"
                - "{{ ubtu_18_010003_crypttab_status.stdout_lines }}"
        when: ubtu_18_010003_crypttab_status.stdout | length > 0
  when:
      - ubtu_18_010003
  tags:
      - UBTU-18-010003
      - CAT2
      - CCI-001199
      - CCI-002475
      - CCI-002476
      - SRG-OS-000185-GPOS-00079
      - SV-219150r610963_rule
      - V-219150
      - encryption
      - mounts

- name: "MEDIUM | UBTU-18-010016 | PATCH | Advance package Tool (APT) must be configured to prevent the installation of patches, service packs, device drivers, or Ubuntu operating system components without verification they have been digitally signed using a certificate that is recognized and approved by the organization."
  block:
      - name: "MEDIUM | UBTU-18-010016 | AUDIT | Advance package Tool (APT) must be configured to prevent the installation of patches, service packs, device drivers, or Ubuntu operating system components without verification they have been digitally signed using a certificate that is recognized and approved by the organization. | Find AllowUnauthenticated true"
        shell: "grep 'AllowUnauthenticated \"true\"' /etc/apt/apt.conf.d/* | cut -d: -f1"
        changed_when: false
        failed_when: false
        register: ubtu_18_010016_apt_allowunauthenticated_status

      - name: "MEDIUM | UBTU-18-010016 | PATCH | Advance package Tool (APT) must be configured to prevent the installation of patches, service packs, device drivers, or Ubuntu operating system components without verification they have been digitally signed using a certificate that is recognized and approved by the organization. | Fix AllowUnauthenticated to false"
        replace:
            path: "{{ item }}"
            regexp: 'AllowUnauthenticated "true"'
            replace: 'AllowUnauthenticated "false"'
        with_items:
            - "{{ ubtu_18_010016_apt_allowunauthenticated_status.stdout_lines }}"
        when: ubtu_18_010016_apt_allowunauthenticated_status.stdout | length > 0
  when:
      - ubtu_18_010016
  tags:
      - UBTU-18-010016
      - CAT2
      - CCI-001749
      - SRG-OS-000366-GPOS-00153
      - SV-219155r610963_rule
      - V-219155
      - apt

- name: "MEDIUM | UBTU-18-010017 | PATCH | The Ubuntu operating system must be configured so that Advance package Tool (APT) removes all software components after updated versions have been installed."
  block:
      - name: "MEDIUM | UBTU-18-010017 | AUDIT | The Ubuntu operating system must be configured so that Advance package Tool (APT) removes all software components after updated versions have been installed. | Find Remove-Unused-Kernel-Packages"
        shell: "grep -i 'remove-unused-kernel-packages \"false\"' /etc/apt/apt.conf.d/* | cut -d: -f1"
        changed_when: false
        failed_when: false
        register: ubtu_18_010017_remove_unused_kernel_packages_status

      - name: "MEDIUM | UBTU-18-010017 | AUDIT | The Ubuntu operating system must be configured so that Advance package Tool (APT) removes all software components after updated versions have been installed. | Find Remove-Unused-Dependencies"
        shell: "grep -i 'remove-unused-dependencies \"false\"' /etc/apt/apt.conf.d/* | cut -d: -f1"
        changed_when: false
        failed_when: false
        register: ubtu_18_010017_remove_unused_dependencies_status

      - name: "MEDIUM | UBTU-18-010017 | PATCH | The Ubuntu operating system must be configured so that Advance package Tool (APT) removes all software components after updated versions have been installed. | Set Remove-Unused-Kernel-Packages"
        lineinfile:
            path: "{{ item.path }}"
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
            create: true
            mode: 644
            owner: root
            group: root
        with_items:
            - { path: "{{ (ubtu_18_010017_remove_unused_kernel_packages_status.stdout | length == 0 ) | ternary('/etc/apt/apt.conf.d/50unattended-upgrades',ubtu_18_010017_remove_unused_kernel_packages_status.stdout) }}", regexp: 'Unattended-Upgrade::Remove-Unused-Kernel-Packages', line: 'Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";' }
            - { path: "{{ (ubtu_18_010017_remove_unused_dependencies_status.stdout | length == 0 ) | ternary('/etc/apt/apt.conf.d/50unattended-upgrades',ubtu_18_010017_remove_unused_dependencies_status.stdout) }}", regexp: 'Unattended-Upgrade::Remove-Unused-Dependencies', line: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";' }
        loop_control:
            label: "{{ item.line }}"
  when:
      - ubtu_18_010017
  tags:
      - UBTU-18-010017
      - CAT2
      - CCI-002617
      - SRG-OS-000437-GPOS-00194
      - SV-219156r610963_rule
      - V-219156
      - apt

- name: "MEDIUM | UBTU-18-010021 | PATCH | The Ubuntu operating system must deploy Endpoint Security for Linux Threat Prevention (ENSLTP)."
  package:
      name: mfetp
      state: present
  when:
      - ubtu_18_010021
      - '"mfetp" not in ansible_facts.packages'
  tags:
      - UBTU-18-010021
      - CAT2
      - CCI-001233
      - SRG-OS-000191-GPOS-00080
      - SV-219159r610963_rule
      - V-219159
      - ensltp
