---

- name: Gather distribution info
  ansible.builtin.setup:
      gather_subset: distribution,!all,!min
  when:
      - ansible_distribution is not defined
  tags:
      - always

# - name: Check OS version and family
#   assert:
#       # that: ansible_os_family == 'Ubuntu' and ansible_distribution_major_version is version_compare('18', '==')
#       msg: "This role can only be run against Ubuntu 18. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
#       that:
#           - ansible_os_family == 'Ubuntu'
#           - ansible_distribution_major_version is version_compare('18', '==')
#   tags:
#       - always

# - name: Check ansible version
#   assert:
#       that: ansible_version.full is version_compare(ubtu18stig_min_ansible_version, '>=')
#       msg: You must use Ansible {{ ubtu18stig_min_ansible_version }} or greater
#   tags:
#       - always

- name: Gather the package facts before prelim
  ansible.builtin.package_facts:
      manager: auto
  tags:
      - always

- name: Include prelim tasks
  ansible.builtin.import_tasks: prelim.yml
  tags:
      - prelim_tasks

- name: Gather the package facts after prelim
  ansible.builtin.package_facts:
      manager: auto
  tags:
      - always

- name: Include CAT I patches
  ansible.builtin.import_tasks: fix-cat1.yml
  when: ubtu18stig_cat1_patch
  tags:
      - cat1
      - high

- name: Include CAT II patches
  ansible.builtin.import_tasks: fix-cat2.yml
  when: ubtu18stig_cat2_patch | bool
  tags:
      - cat2
      - medium

- name: Include CAT III patches
  ansible.builtin.import_tasks: fix-cat3.yml
  when: ubtu18stig_cat3_patch | bool
  tags:
      - cat3
      - low

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Reboot system
  block:
      - name: reboot system if not skipped
        ansible.builtin.reboot:
        when:
            - not ubtu18_skip_reboot

      - name: Warning a reboot required but skip option set
        ansible.builtin.debug:
            msg: "Warning!! changes have been made that require a reboot to be implemented but skip reboot was set - Can affect compliance check results"
        changed_when: true
        when:
            - ubtu18_skip_reboot

- name: If Warnings found Output count and control IDs affected
  ansible.builtin.debug:
      msg:
          - "You have {{ warn_count }} Warning(s) that require investigation(s). Their ID’s are listed below:"
          - "{{ warn_control_list }}"
  when: warn_count != 0
