---
- name: "PRELIM | Run apt update"
  apt:
      update_cache: yes

- name: "PRELIM | UBTU-18-010000 | Check whether machine is UEFI-based"
  stat:
    path: /sys/firmware/efi
  register: ubtu_18_sys_firmware_efi
  when:
  - ubtu_18_010000
  tags:
  - cat1
  - high

- name: "PRELIM | UBTU-18-010150 | dconf setup"
  block:
      - name: "PRELIM | dconf setup | UBTU-18-010150 | check for dconf"
        command: which dconf
        changed_when: false
        failed_when: false
        register: ubtu18stig_dconf_status

      - name: "PRELIM | dconf setup | UBTU-18-010150  | install if missing"
        package:
            name: dconf-cli
            state: present
        when: 
            - ubtu18stig_dconf_status.stdout == ""
            - "'dconf-cli' not in ansible_facts.packages"
  when:
      - ubtu_18_010150
  tags:
      - cat1
      - high

- name: "PRELIM | Install auditd"
  package:
      name: auditd
      state: present
  when:
      - "'auditd' not in ansible_facts.packages"
      - ubtu_18_010006

- name: "PRELIM | Intall audisp-remote plugin"
  package:
      name: audispd-plugins
      state: present
  when:
      - ubtu_18_010007 or
        ubtu_18_010025