---

# - name: update grub
#   command: update-grub
#   when:
#       - not ubtu18stig_skip_for_travis
#       - not ubtu18stig_system_is_container

- name: reload gdm
  command: dpkg-reconfigure gdm3

- name: dconf update
  command: dconf update

- name: restart sshd
  service:
      name: sshd
      state: restarted
  when:
      - "'openssh-server' in ansible_facts.packages"

- name: restart auditd
  service:
      name: auditd
      state: restarted

- name: restart chrony
  service: 
      name: chrony
      state: restarted

